# Generated by ChatGPT on 2025-09-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis_app", "0005_cachedsubdivision_legacy_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="selected_pu_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cachedpu",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cachedpu",
            name="embedding_updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="cachedpu",
            name="normalized_full_name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="cachedpu",
            name="normalized_short_name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="cachedsubdivision",
            name="parent_pu_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
