# Generated by ChatGPT on 2025-09-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis_app", "0006_pu_cache_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cachedpu",
            name="portal_pu_id",
            field=models.UUIDField(db_index=True, unique=True),
        ),
        migrations.RemoveField(
            model_name="cachedpu",
            name="embedding",
        ),
        migrations.RemoveField(
            model_name="cachedpu",
            name="embedding_updated_at",
        ),
        migrations.AddField(
            model_name="cachedpu",
            name="embedding_full",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cachedpu",
            name="embedding_short",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
