# Generated by Django 5.2.11 on 2026-02-15 11:24

import base64
import hashlib
import os

from django.conf import settings
from django.db import migrations, models


def _derive_key() -> bytes:
    key_from_env = os.getenv("PORTAL_DB_FERNET_KEY", "").strip()
    if key_from_env:
        return key_from_env.encode("utf-8")
    digest = hashlib.sha256(settings.SECRET_KEY.encode("utf-8")).digest()
    return base64.urlsafe_b64encode(digest)


def _get_test_params() -> dict:
    def env_or(primary: str, fallback: str) -> str:
        return os.getenv(primary) or os.getenv(fallback, "")

    return {
        "host": env_or("PORTAL_DB_TEST_HOST", "PORTAL_DB_HOST"),
        "port": int(env_or("PORTAL_DB_TEST_PORT", "PORTAL_DB_PORT") or 5432),
        "db_name": env_or("PORTAL_DB_TEST_NAME", "PORTAL_DB_NAME"),
        "user": env_or("PORTAL_DB_TEST_USER", "PORTAL_DB_USER"),
        "password": env_or("PORTAL_DB_TEST_PASSWORD", "PORTAL_DB_PASSWORD"),
    }


def _encrypt_password(password: str) -> str:
    if not password:
        return ""
    try:
        from cryptography.fernet import Fernet
    except ImportError:
        return ""
    return Fernet(_derive_key()).encrypt(password.encode("utf-8")).decode("utf-8")


def bootstrap_portal_settings(apps, schema_editor):
    model = apps.get_model("analysis_app", "PortalDbConnectionSettings")
    if model.objects.exists():
        return

    params = _get_test_params()
    model.objects.create(
        profile="TEST",
        host=params["host"],
        port=params["port"],
        db_name=params["db_name"],
        user=params["user"],
        password_encrypted=_encrypt_password(params["password"]),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("analysis_app", "0008_cachedsubdivision_normalized_short_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalDbConnectionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.CharField(
                        choices=[("TEST", "Тестовая"), ("PROD", "Боевая")],
                        default="TEST",
                        max_length=10,
                    ),
                ),
                ("host", models.CharField(blank=True, default="", max_length=255)),
                ("port", models.PositiveIntegerField(default=5432)),
                ("db_name", models.CharField(blank=True, default="", max_length=255)),
                ("user", models.CharField(blank=True, default="", max_length=255)),
                ("password_encrypted", models.TextField(blank=True, default="")),
                ("last_check_ok", models.BooleanField(default=None, null=True)),
                ("last_check_error", models.TextField(blank=True, default="")),
                ("last_check_at", models.DateTimeField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Настройка подключения к базе данных",
                "verbose_name_plural": "Настройка подключения к базе данных",
            },
        ),
        migrations.RunPython(bootstrap_portal_settings, migrations.RunPython.noop),
    ]
