# Generated by Django 5.2.11 on 2026-02-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis_app", "0009_portaldbconnectionsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlags",
            fields=[
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("debug_mode", models.BooleanField(default=False, verbose_name="DEBUG режим")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Флаги приложения",
                "verbose_name_plural": "Флаги приложения",
            },
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="debug_pipeline",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
