# Generated by Django 5.2.5 on 2026-02-20 00:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("analysis_app", "0015_analysisparagraph_source_table_header_cells"),
    ]

    operations = [
        migrations.CreateModel(
            name="SvodkaTemplate",
            fields=[
                (
                    "template_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("scope", models.CharField(choices=[("pu", "PU"), ("general", "Общая сводка")], max_length=20)),
                ("pu_id", models.CharField(blank=True, default="", max_length=64)),
                ("pu_name", models.CharField(blank=True, default="", max_length=255)),
                ("file", models.FileField(blank=True, null=True, upload_to="svodka_templates/")),
                ("begin_marker", models.CharField(default="[BEGIN]", max_length=32)),
                ("end_marker", models.CharField(default="[END]", max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Шаблон сводки",
                "verbose_name_plural": "Шаблоны сводки",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("scope", "pu_id"),
                        name="uniq_active_svodka_template_per_scope_pu",
                    )
                ],
            },
        ),
    ]
