# Generated by Django 5.2.11 on 2026-02-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis_app", "0018_analysisrun_progress_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlags",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("debug_mode", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Флаги",
                "verbose_name_plural": "Флаги",
            },
        ),
    ]
