# Generated by Django 5.2.11 on 2026-02-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis_app", "0019_featureflags"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="debug_package_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="debug_package_file",
            field=models.FileField(blank=True, null=True, upload_to="debug_packages/"),
        ),
    ]
