# Generated by Django 5.2.11 on 2026-02-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis_app", "0020_analysisrun_debug_package_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="debug_pipeline",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="debug_pipeline_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
