# Generated by Django 5.2.11 on 2026-02-26 20:21

from django.db import migrations, models


def _status_from_flag(flag):
    if flag is True:
        return "green"
    if flag is False:
        return "red"
    return "neutral"


def _populate_denormalized_fields(apps, schema_editor):
    AnalysisResult = apps.get_model("analysis_app", "AnalysisResult")
    for result in AnalysisResult.objects.select_related("paragraph").all().iterator():
        match_result = result.match_result or {}
        matched = bool(match_result.get("matched"))
        text = (getattr(result.paragraph, "text", "") or "")
        result.matched = matched
        result.title = f"Событие {result.paragraph.idx}" + ("" if matched else " — в базе данных не найдено")
        result.preview = text[:80] + ("…" if len(text) > 80 else "")
        result.status_timestamp = "neutral"
        result.status_subdivision = "neutral"
        result.status_offenders = "neutral"
        result.status_event_type = _status_from_flag(match_result.get("event_type_ok"))
        result.status_article = match_result.get("article_status") or _status_from_flag(match_result.get("article_ok"))
        result.save(update_fields=[
            "matched",
            "title",
            "preview",
            "status_timestamp",
            "status_subdivision",
            "status_offenders",
            "status_event_type",
            "status_article",
        ])


def _noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("analysis_app", "0021_analysisrun_debug_pipeline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="detail_payload_cache",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="detail_payload_cached_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="matched",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="preview",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="status_article",
            field=models.CharField(blank=True, default="neutral", max_length=16),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="status_event_type",
            field=models.CharField(blank=True, default="neutral", max_length=16),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="status_offenders",
            field=models.CharField(blank=True, default="neutral", max_length=16),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="status_subdivision",
            field=models.CharField(blank=True, default="neutral", max_length=16),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="status_timestamp",
            field=models.CharField(blank=True, default="neutral", max_length=16),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddIndex(
            model_name="analysisparagraph",
            index=models.Index(
                fields=["run", "idx"], name="analysis_paragraph_run_idx_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysisresult",
            index=models.Index(
                fields=["paragraph"], name="analysis_result_paragraph_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisparagraph",
            constraint=models.UniqueConstraint(
                fields=("run", "idx"), name="uniq_analysis_paragraph_run_idx"
            ),
        ),
        migrations.RunPython(_populate_denormalized_fields, _noop),
    ]
