# Generated by Django 5.2.12 on 2026-03-05 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis_app", "0022_analysisresult_detail_payload_cache_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="svodkatemplate",
            name="anchor_match_threshold",
            field=models.FloatField(
                default=0.6,
                help_text="Чем ниже — тем проще найти якорь при небольших изменениях, но выше риск ложных совпадений. Рекомендовано 0.55–0.70.",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="Порог совпадения якоря",
            ),
        ),
    ]
