# Generated by Django 5.2.12 on 2026-03-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis_app", "0023_svodkatemplate_anchor_match_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrun",
            name="slicing_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
